### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by dudenhofer** [platformsh/template-symfony4#10]
I was testing this in the UI. The build appears to work fine, but when visiting the site, I get:

```Fatal error: Uncaught Symfony\Component\Routing\Exception\NoConfigurationException in /app/var/cache/prod/srcProdProjectContainerUrlMatcher.php:34 Stack trace: #0 /app/vendor/symfony/routing/Matcher/UrlMatcher.php(95): srcProdProjectContainerUrlMatcher->match('/') #1 /app/vendor/symfony/routing/Router.php(262): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request)) #2 /app/vendor/symfony/http-kernel/EventListener/RouterListener.php(109): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request)) #3 /app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfon in /app/vendor/symfony/http-kernel/EventListener/RouterListener.php on line 139```

**Comment by pjcdawkins** [comment]
Doesn't that just mean it's a Symfony project with no routes, i.e. "404, you haven't written any code yet"

**Comment by Crell** [comment]
I believe that's the case, yes.  Not much we can do on our side for that without building out Symfony sample content, which I'm not game to do. :-)
