### ISSUE TITLE
Error while executing build hooks

### ISSUE THREAD

**Issue by undebutant** [platformsh/template-symfony4#8]
Hello,

I cloned the template and tried to upload it to my platform.sh project, however during build hooks execution, I encountered the following error :

```
  Executing build hook...
    W: /bin/sh: 1: bin/console: Permission denied
    W: /bin/sh: 2: bin/console: Permission denied
```

I figured out a way to fix it by editing the [build hooks from .platform.app.yaml](https://github.com/platformsh/template-symfony4/blob/master/.platform.app.yaml#L21-L22), by simply adding ```php``` before each line:

```
        php bin/console assets:install --no-debug
        php bin/console cache:clear
```

Is this workaround fine, or did I miss something ?

**Comment by emirb** [comment]
It looks like a permission issues, so you have to make a `bin/console` executable, or prefix it with php to actually execute it with php. Otherwise, `chmod +x bin/console` will do it.

**Comment by undebutant** [comment]
Indeed, thanks a lot !
